version: '3'

volumes:
  pgdata:
  static_files:

services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: gunicorn -w 4 blog.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
      - static_files:/static_files
    ports:
      - 8000:8000
    depends_on:
      - db
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - web
    volumes:
      - static_files:/static_files

